language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm test

after_success:
  - npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: ntrs
  run: npm run build
